set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS33} [get_ports hdmi_rx_txen]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD TMDS_33} [get_ports TMDS_0_clk_n]
set_property -dict {PACKAGE_PIN T1 IOSTANDARD TMDS_33} [get_ports TMDS_0_clk_p]
set_property -dict {PACKAGE_PIN Y1 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_n[0]}]
set_property -dict {PACKAGE_PIN W1 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_p[0]}]
set_property -dict {PACKAGE_PIN AB1 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_n[1]}]
set_property -dict {PACKAGE_PIN AA1 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_p[1]}]
set_property -dict {PACKAGE_PIN AB2 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_n[2]}]
set_property -dict {PACKAGE_PIN AB3 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_p[2]}]


set_property PACKAGE_PIN M17 [get_ports {mm2s_frame_ptr_in_0[5]}]
set_property PACKAGE_PIN K13 [get_ports {mm2s_frame_ptr_in_0[4]}]
set_property PACKAGE_PIN J16 [get_ports {mm2s_frame_ptr_in_0[3]}]
set_property PACKAGE_PIN H17 [get_ports {mm2s_frame_ptr_in_0[2]}]
set_property PACKAGE_PIN G22 [get_ports {mm2s_frame_ptr_in_0[1]}]
set_property PACKAGE_PIN G21 [get_ports {mm2s_frame_ptr_in_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mm2s_frame_ptr_in_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mm2s_frame_ptr_in_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mm2s_frame_ptr_in_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mm2s_frame_ptr_in_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mm2s_frame_ptr_in_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mm2s_frame_ptr_in_0[0]}]

set_property PACKAGE_PIN Y13 [get_ports {LEDR[0]}]
set_property PACKAGE_PIN W15 [get_ports {LEDR[1]}]
set_property PACKAGE_PIN W16 [get_ports {LEDR[2]}]
set_property PACKAGE_PIN V15 [get_ports {LEDR[3]}]
set_property PACKAGE_PIN U16 [get_ports {LEDR[4]}]
set_property PACKAGE_PIN T16 [get_ports {LEDR[5]}]
set_property PACKAGE_PIN T15 [get_ports {LEDR[6]}]
set_property PACKAGE_PIN T14 [get_ports {LEDR[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDR[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDR[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDR[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDR[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDR[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDR[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDR[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDR[0]}]

set_property -dict { PACKAGE_PIN AB21  IOSTANDARD LVCMOS33 } [get_ports { tx_0  }]; #JB[2] }]; #IO_L14N_T2_SRCC_15 Sch=jb[2]
set_property -dict { PACKAGE_PIN AB20  IOSTANDARD LVCMOS33 } [get_ports { rx_0  }]; #JB[3] }]; #IO_L13N_T2_MRCC_15 Sch=jb[3]
